### ISSUE TITLE
ブログ画像スクレイピング

### ISSUE THREAD

**Issue by asuka980810** [haradai1262/keyakizaka46-mining#1]
csvに書き出したデータからブログ画像を保存するのを見たのですが、欅坂ではなく乃木坂の保存するコード作成して貰えませんか？

**Comment by haradai1262** [comment]
読み込むcsvファイル(keyakizaka46_blog_20190217.csv)を乃木坂へ変更すれば動作しますよ！

**Comment by asuka980810** [comment]
日向坂のコードは作成しませんか？
